version: '2'
services:
  build-base:
    build:
      context: .
      dockerfile: base/Dockerfile
    image: machine-learning-base

  build-ml:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: machine-learning
    depends_on: 
      - build-base
    command: is_built