version: '2'
services:
  build-base:
    build:
      context: .
      dockerfile: base/Dockerfile
    image: machine-learning-base

  build-model:
    build:
      context: .
      dockerfile: model/Dockerfile
    image: machine-learning-model
    depends_on:
      - build-base

  build-ml:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: machine-learning
    depends_on: 
      - build-model
    command: is_built