version: '2'
services:
  tasks-server-container:
    image: machine-learning
    command: python -m utest.test_suite
    environment:
       - PYTHONPATH=/usr/src/app
    env_file:
      - local.env
    # ports:
    #   - 8001:8001
      # - 9090:9090
    volumes:
      - .:/usr/src/app
      - ~/Documents/pickles:/usr/src/app/pickles:ro